//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeXemPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public string email { get; set; }
        public string matKhau { get; set; }
        public string ten { get; set; }
        public string sdt { get; set; }
        public Nullable<System.DateTime> ngaySinh { get; set; }
    }
}
